### ISSUE TITLE
lua:interp.lua require 'winapi', 

### ISSUE THREAD

**Issue by xingchch** [stevedonovan/AndroLua#6]
luarocks  intall winapi under ubuntu. it shows:
This rockspec for winapi does not support unix, linux platforms.
So , May i know how to run interp.lua under linux?

**Comment by stevedonovan** [comment]
There is a Linux-specific `ashell`, which must be made executable.  If using lua 5.2, the first code line `require 'socket'` must become `local socket = require 'socket'`.  By default, alshell also opens the log  (any print in your activities goes here).  If you don't need that, then `./alshell localhost no` after `adb forward tcp:3333 tcp:3333` should work fine.

I will update the readme and make these little fixes!

**Comment by xingchch** [comment]
thanks @stevedonovan .
